<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        $users = [

            [
            'name' => 'Admin User',
            'email' => 'admin@example.com',
            'phone' => '081234567890',
            'password' => Hash::make('password'),
            'role' => 'admin',
            'position' => null,
            'position_order' => 999,
            'presence_status' => 'ada',
            'presence_updated_at' => null,
            'is_active' => true,
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
                'name' => 'Receptionist User',
                'email' => 'receptionist@example.com',
                'phone' => '081234567891',
                'password' => Hash::make('password'),
                'role' => 'receptionist',
                'position' => null,
                'position_order' => 999,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drs Pandi, S.H., M.H.',
                'email' => 'pandi@ptapapuabarat.com',
                'phone' => '0811551456',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Ketua',
                'position_order' => 1,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Drs. H. Moh. Faishol Hasanuddin, S.H., M.H.',
                'email' => 'moh.faishol.hasanuddin@ptapapuabarat.com',
                'phone' => '081232567799',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Wakil Ketua',
                'position_order' => 2,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drs. Muhammad Takdir, S.H., M.H.',
                'email' => 'muhammad.takdir@ptapapuabarat.com',
                'phone' => '085242703739',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Hakim Tinggi',
                'position_order' => 3,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drs Basyirun, M.H.',
                'email' => 'basyirun@ptapapuabarat.com',
                'phone' => '081230804025',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Hakim Tinggi',
                'position_order' => 4,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drs. Rahmat Farid, M.H.',
                'email' => 'rahmat.farid@ptapapuabarat.com',
                'phone' => '081345218327',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Hakim Tinggi',
                'position_order' => 5,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nurmansyah, S.Ag., M.H',
                'email' => 'nurmansyah@ptapapuabarat.com',
                'phone' => '081222138949',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Sekretaris',
                'position_order' => 6,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. Imran, S.Ag., S.H., M.H.',
                'email' => 'imran@ptapapuabarat.com',
                'phone' => '081344027540',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera',
                'position_order' => 7,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khoiriyah, S.Ag., M.H.',
                'email' => 'khoiriyah@ptapapuabarat.com',
                'phone' => '081248659233',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Muda Hukum',
                'position_order' => 8,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Musa Sholawat, S.H.I.',
                'email' => 'musa.sholawat@ptapapuabarat.com',
                'phone' => '081248375717',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Muda Banding',
                'position_order' => 9,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raswin, S.H.I.',
                'email' => 'raswin@ptapapuabarat.com',
                'phone' => '08114904111',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Kepala Bagian Umum dan Keuangan',
                'position_order' => 10,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Syamsul Bahri, S.H.I.',
                'email' => 'syamsul.bahri@ptapapuabarat.com',
                'phone' => '082141677177',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Kepala Bagian Perencanaan dan Kepegawaian',
                'position_order' => 11,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nasir Maswatu, S.H.I.',
                'email' => 'nasir.maswatu@ptapapuabarat.com',
                'phone' => '082239899026',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Pengganti',
                'position_order' => 12,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Akram, S.H., M.H.',
                'email' => 'akram@ptapapuabarat.com',
                'phone' => '082258729884',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Pengganti',
                'position_order' => 13,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zubaidah Hi Hamzah, S.H.',
                'email' => 'zubaidah.hi.hamzah@ptapapuabarat.com',
                'phone' => '082198590925',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Pengganti',
                'position_order' => 14,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Missah Hamzah Suara, S.H.',
                'email' => 'missah.hamzah.suara@ptapapuabarat.com',
                'phone' => '081247288998',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Panitera Pengganti',
                'position_order' => 15,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Manik Rochmani, S.H.',
                'email' => 'manik.rochmani@ptapapuabarat.com',
                'phone' => '082238794290',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Kepala Sub Bagian Rencana Program dan Anggaran',
                'position_order' => 16,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ummu Mukhlisa, S.H., M.H.',
                'email' => 'ummu.mukhlisa@ptapapuabarat.com',
                'phone' => '085254101684',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Kepala Sub Bagian Tata Usaha dan Rumah Tangga',
                'position_order' => 17,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Suria Kencana, S.E.',
                'email' => 'suria.kencana@ptapapuabarat.com',
                'phone' => '08114801296',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Kepala Sub Bagian Keuangan dan Pelaporan',
                'position_order' => 18,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Muslim Amin, A.Md.A.B.',
                'email' => 'muslim.amin@ptapapuabarat.com',
                'phone' => '081222511152',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Arsiparis Terampil',
                'position_order' => 19,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sitti Suriyani Tuahuns, S.Pd.SD',
                'email' => 'sitti.suriyani.tuahuns@ptapapuabarat.com',
                'phone' => '085241057079',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Pengadministrasi Perkantoran',
                'position_order' => 20,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad Nur Fajri, S.H.',
                'email' => 'ahmad.nur.fajri@ptapapuabarat.com',
                'phone' => '082333106343',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Analis Perkara Peradilan',
                'position_order' => 21,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Akbar, S.H.',
                'email' => 'akbar@ptapapuabarat.com',
                'phone' => '082199187860',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Analis Perkara Peradilan',
                'position_order' => 22,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHAMMAD LUTFI KHAKIM, A.Md.Kom.',
                'email' => 'muhammad.lutfi.khakim@ptapapuabarat.com',
                'phone' => '081215797615',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Dokumentalis Hukum',
                'position_order' => 23,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'GILANG ARIEF MAULANA, S.E.',
                'email' => 'gilang.arief.maulana@ptapapuabarat.com',
                'phone' => '083129031844',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Analis Pengelolaan Keuangan APBN Ahli Pertama',
                'position_order' => 24,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MUHJAR NIAS DANI, S.Kom.',
                'email' => 'muhjar.nias.dani@ptapapuabarat.com',
                'phone' => '081240170314',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Penata Kelola Sistem dan Teknologi Informasi',
                'position_order' => 25,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YUDHIS SALVANIA PRADANA, S.I.Kom.',
                'email' => 'yudhis.salvania.pradana@ptapapuabarat.com',
                'phone' => '089617013769',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Penata Keprotokolan',
                'position_order' => 26,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SAID SALASA',
                'email' => 'said.salasa@ptapapuabarat.com',
                'phone' => '081344597651',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Pengadministrasi Perkantoran',
                'position_order' => 27,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'IKSAN OHORELLA',
                'email' => 'iksan.ohorella@ptapapuabarat.com',
                'phone' => '081240772222',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Operator Layanan Operasional',
                'position_order' => 28,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HAMZAH SYAM',
                'email' => 'hamzah.syam@ptapapuabarat.com',
                'phone' => '081247784532',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Operator Layanan Operasional',
                'position_order' => 29,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'YATINO',
                'email' => 'yatino@ptapapuabarat.com',
                'phone' => '082199439393',
                'password' => Hash::make('ptapabar'),
                'role' => 'employee',
                'position' => 'Operator Layanan Operasional',
                'position_order' => 30,
                'presence_status' => 'ada',
                'presence_updated_at' => null,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('users')->insert($users);
    }
}